### Local - Home route
GET https://cse341-ujj4.onrender.com

###

### Local - Get all contacts
GET https://cse341-ujj4.onrender.com/contacts

###

### Local - Get one contact by ID
GET https://cse341-ujj4.onrender.com/contacts/6a47d82c3e9e768bc8ddd374